[log_notifs]
    script = ~/.config/rofi/notification/dunst_logger.py
    # script = ~/Scripts/dmenu/dmplay.sh

[urgency_low]
    background = "#111111"
    foreground = "#ffffff"
	highlight = "#404355"
    timeout = 3
    # Icon for notifications with low urgency
    #default_icon = dialog-information

[urgency_normal]
    background = "#111111"
    foreground = "#ffffff"
	frame_color = "#404355"
	highlight = "#50F97B"
    timeout = 5
    override_pause_level = 30
    # Icon for notifications with normal urgency
    default_icon = dialog-information

[urgency_critical]
    background = "#111111"
    foreground = "#ffffff"
    frame_color = "#d54e53"
	highlight = "#d54e53, #f0f0f0"
    timeout = 0
    override_pause_level = 60
    # Icon for notifications with critical urgency
    default_icon = dialog-warning