[microphone]
    appname = "system"
    stack_tag = "microphone"
    format = "%p"
    timeout = 2
    max_icon_size = 32
    history_ignore = true

[microphone-mute]
    appname = "system"
    stack_tag = "microphone"
    summary = "mute"
    highlight = "#d54e53"
    format = "[OFF]"
    timeout = 2
    history_ignore = true