[vesktop]
    appname="vesktop"
    max_icon_size = 64
    urgency = low
    timeout = 5

# Notifications from vesktop are parsed and sent as app discord so that we can modify the (A)ction
# [vesktop]
    # desktop_entry="vesktop"
    # skip_display = true
    # history_ignore = true
    # script = "~/.config/hypr/scripts/discord-notification.sh"