[windscribe-browser-disconnected]
    appname = "Waterfox"
    summary = "Windscribe"
    body = "Connection to Windscribe has been terminated"
    timeout = 10
    urgency = "critical"
    history_ignore = true
    action_name = ""

[windscribe-browser]
    appname = "Waterfox"
    summary = "Windscribe"
    timeout = 2
    urgency = "low"
    history_ignore = true
    action_name = ""