# Variables
source = $HOME/.config/hypr/config/variables/global.conf

$loginSectionImage = $HOME/.assets/images/lock-screen/windows-95-box.png

general {
    no_fade_in = false
    no_fade_out = false
    grace = 0
    disable_loading_bar = false
}

background {
    # monitor = $PRIMARY_MONITOR
    color = rgba(0, 128, 128, 1)
    blur_passes = 0
    contrast = 1
    brightness = 1
    vibrancy = 1
    vibrancy_darkness = 0
}

# Login section image
image {
    monitor = $PRIMARY_MONITOR
    halign = center
    valign = center
    size = 350
    position = -100, 250

    rounding = 0

    border_size = 0
    path = $loginSectionImage
}

# Question button
shape {
    monitor = $PRIMARY_MONITOR
    halign = center
    valign = center
    size = 37, 32
    position = 390, 400
    zindex = 1

    color = rgba(255, 0, 0, 0)
    onclick = systemctl reboot --now
}

# Close button
shape {
    monitor = $PRIMARY_MONITOR
    halign = center
    valign = center
    size = 37, 32
    position = 435, 400
    zindex = 1

    color = rgba(255, 0, 0, 0)
    onclick = systemctl poweroff --now
}

# Ok button
shape {
    monitor = $PRIMARY_MONITOR
    halign = center
    valign = center
    size = 190, 55
    position = 345, 320
    zindex = 1

    color = rgba(255, 0, 0, 0)
    onclick = [[ ! -e /tmp/sleepy-eepy ]] && touch /tmp/sleepy-eepy && systemctl suspend --now
}

# Cancel button
shape {
    monitor = $PRIMARY_MONITOR
    halign = center
    valign = center
    size = 190, 55
    position = 345, 245
    zindex = 1

    color = rgba(255, 0, 0, 0)
    onclick = systemctl hibernate
}

# Username label
label {
    monitor = $PRIMARY_MONITOR
    halign = center
    valign = center
    position = -167, 230

    font_size = 23
    text = morder110
    color = rgb(0, 0, 0)
    font_family = MS Sans Serif 7 Regular
}

# Password field
input-field {
    monitor = $PRIMARY_MONITOR
    halign = center
    valign = center
    size = 326, 50
    position = -91, 154

    invert_numlock = false
    fade_on_empty = false
    hide_input = false
    outline_thickness = 3
    rounding = 0
    inner_color = rgba(0, 0, 0, 0)
    outer_color = rgba(0, 0, 0, 0)
    check_color = rgba(0, 0, 0, 0)
    fail_color = rgba(255, 0, 0, 1)
    capslock_color = rgba(254, 122, 43, 1)
    bothlock_color = rgba(254, 122, 43, 1)

    placeholder_text = # Blank
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>

    font_family = MS Sans Serif 7 Regular
    font_color = rgb(0, 0, 0)
    dots_text_format = x
    dots_center = false
    dots_spacing = 0
    dots_size = 0.5
}

# Attempts label
label {
    monitor = $PRIMARY_MONITOR
    halign = center
    valign = center
    position = 175, 153

    font_size = 20
    text = cmd[update:3000] [[ ! $ATTEMPTS = 0 ]] && echo "Skill issues: $ATTEMPTS"
    color = rgb(255, 0, 0)
    font_family = MS Sans Serif 7 Regular
}

# Hint label
label {
    monitor = $PRIMARY_MONITOR
    halign = center
    valign = center
    position = -180, 100

    font_size = 12
    text = cmd[update:3000] [[ $ATTEMPTS -ge 2 ]] && echo "<b>Hint: You know ;)</b>"
    color = rgb(0, 0, 0)
    font_family = MS Sans Serif 7 Regular
}