#!/bin/bash

# ===== YADM config =====
MACHINE_ID=$(cat /etc/machine-id)
if [[ "${MACHINE_ID}" = "2f709ee92a8d45d19c21ebdbc3b76844" ]]; then
    yadm config local.hostname home-desktop
elif [[ "${MACHINE_ID}" = "adfbb494b5c34576bbe476b6d901fcec" ]]; then
    yadm config local.hostname lenovo-laptop
fi

# ===== Gitconfig =====
yadm gitconfig --global user.name 'morder110'
yadm gitconfig --global init.defaultBranch 'master'

yadm gitconfig --global core.editor 'code --wait --new-window'

yadm gitconfig --global merge.tool "vscode"
yadm gitconfig --global mergetool.vscode.cmd 'code --wait --new-window --merge $LOCAL $REMOTE $BASE $MERGED'

yadm gitconfig --global diff.tool "vscode"
yadm gitconfig --global difftool.vscode.cmd 'code --wait --new-window --diff $LOCAL $REMOTE'

# ===== Hypr keybinds active =====
KEYBINDS_DIR="$HOME/.config/hypr/config/keybinds"
if [ ! -f "$KEYBINDS_DIR/keyboard/active.conf" ]; then
    cp "$KEYBINDS_DIR/keyboard/active.conf.default" "$KEYBINDS_DIR/keyboard/active.conf"
fi

if [ ! -f "$KEYBINDS_DIR/mouse/active.conf" ]; then
    cp "$KEYBINDS_DIR/mouse/active.conf.default" "$KEYBINDS_DIR/mouse/active.conf"
fi