$PRIMARY_MONITOR = DP-1
$PRIMARY_MONITOR_ASPECT_RATIO = 16x9
$SECONDARY_MONITOR = HDMI-A-1
$SECONDARY_MONITOR_ASPECT_RATIO = 16x9

# Needed for Flameshot size calculation
$TOP_LEFT_MONITOR = DP-1
$MONITOR_WIDTH_COUNT = 3
$MONITOR_HEIGHT_COUNT = 4