# =====================================================================
# >> VARIABLES
# =====================================================================
    $MOD = SUPER
    $SCRIPTS_DIR = $HOME/.config/hypr/scripts

# =====================================================================
# >> WINDOW & WORKSPACE MANAGEMENT
# =====================================================================
    # Move active window to a workspace (follow)
    unbind = $MOD SHIFT, 5
    unbind = $MOD SHIFT, 6
    unbind = $MOD SHIFT, 7
    unbind = $MOD SHIFT, 8
    unbind = $MOD SHIFT, 9

    # Move active window to a workspace (silent)
    unbind = $MOD ALT, 5
    unbind = $MOD ALT, 6
    unbind = $MOD ALT, 7
    unbind = $MOD ALT, 8
    unbind = $MOD ALT, 9

# =====================================================================
# >> WINDOW & WORKSPACE NAVIGATION
# =====================================================================
    # Switch workspace
    unbind = $MOD, 5
    unbind = $MOD, 6
    unbind = $MOD, 7
    unbind = $MOD, 8
    unbind = $MOD, 9