source=$HOME/.config/hypr/config/variables/global.conf

general {
    lock_cmd = pidof hyprlock || hyprlock # Avoid starting multiple hyprlock instances.
    before_sleep_cmd = $HOME/.config/hypr/scripts/lock.sh # Lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on && sleep 3 && hyprctl dispatch dpms on & # To avoid having to press a key twice to turn on the display. Due to multiple sleep activations, do it again after 3 seconds
}

# Turn off keyboard backlight
listener {
    timeout = $KEYBOARD_BACKLIGHT_TIMEOUT
    on-timeout = brightnessctl -sd tpacpi::kbd_backlight set 0 # Turn off
    on-resume = brightnessctl -rd tpacpi::kbd_backlight # Resore state
}

# Turn off display and pause notifications.
listener {
    timeout = $DISPLAY_TIMEOUT
    on-timeout = hyprctl dispatch dpms off && pkill -SIGUSR1 dunst
    on-resume = hyprctl dispatch dpms on && pidof hyprlock || pkill -SIGUSR2 dunst # Do not resume if on lock screen
}

# Lock screen
listener {
    timeout = $LOCK_TIME
    on-timeout = $HOME/.config/hypr/scripts/lock.sh
}

# Turn off display when locked
listener {
    # TODO: If possible, enable this only when locking screen, then, disable when
    timeout = 20
    on-timeout = pidof hyprlock && hyprctl dispatch dpms off
    on-resume = pidof hyprlock && hyprctl dispatch dpms on
}

# Sleep when locked
listener {
    # TODO: If possible, enable this only when locking screen, then, disable when
    timeout = $SLEEP_WHEN_LOCKED_TIME
    on-timeout = pidof hyprlock && systemctl suspend --now
    # on-timeout = pidof hyprlock && [[ ! -e /tmp/sleepy-eepy ]] && touch /tmp/sleepy-eepy && systemctl suspend --now
    # on-resume = pidof hyprlock && rm /tmp/sleepy-eepy
}