$CONFIG_DIR = $HOME/.config/hypr/config

source = $CONFIG_DIR/settings.conf
source = $CONFIG_DIR/startup.conf
source = $CONFIG_DIR/env.conf
source = $CONFIG_DIR/windowrules.conf # TODO: Config this to be device specific

# Device specific settings
source = $CONFIG_DIR/device.conf

# Keybinds
source = $CONFIG_DIR/keybinds/global.conf

# Theme
source = $CONFIG_DIR/decoration.conf

source = $CONFIG_DIR/monitors/active/monitors.conf
source = $CONFIG_DIR/monitors/active/workspaces.conf