$PRIMARY_MONITOR = eDP-1
$PRIMARY_MONITOR_ASPECT_RATIO = 16x10
$SECONDARY_MONITOR =
$SECONDARY_MONITOR_ASPECT_RATIO =

# Needed for Flameshot size calculation
$TOP_LEFT_MONITOR = eDP-1
$MONITOR_WIDTH_COUNT = 1
$MONITOR_HEIGHT_COUNT = 1