# Window Decoration
$ACTIVE_BORDER_COLOR = rgb(b4befe)
$INACTIVE_BORDER_COLOR = rgb(6c7086)
$BORDER_SIZE = 1
$WINDOW_MARGIN_IN = 0 # Between windows
$WINDOW_MARGIN_OUT = 0 # Edges of screen

# TODO: Set nwg-look themes and cursor using as well as GNOME.

# Theme
$GTK_THEME = # Must be located in `$HOME/.assets/themes/`
$ICON_THEME = # Must be located in `$HOME/.assets/icons/themes/`
$FONT_THEME = # Must be located in `$HOME/.assets/fonts/`
$COLOR_SCHELE = prefer-dark
$CURSOR_THEME = NotwaitaBlack # Hackneyd-Dark # Must be located in `$HOME/.assets/fonts/`
$CURSOR_SIZE = 24