# NOTE: Due to this file being a source in multiple files, exec-once *might* be run multiple times if placed in this file.

# Default
$DEFAULT_BROWSER = waterfox
$DEFAULT_TERMINAL = alacritty
$DEFAULT_FILE_MANAGER = thunar
$DEFAULT_CLI_FILE_MANAGER = yazi

source=$HOME/.config/hypr/config/variables/active.conf

source=$HOME/.config/hypr/config/monitors/active/variables.conf
source=$HOME/.config/hypr/config/variables/decoration.conf
