# NOTE: This is included in the "Devices" section instead of "Keyboard" due to more annoying detection.

# =====================================================================
# >> 2nd F-LAYER NAMES & OTHER SPECIAL KEYS
# =====================================================================
    # Fn - XF86WakeUp
    # Fn + 4 - XF86Sleep (can be bound, but the sleep will ALWAYS trigger)
    # F1 - XF86AudioMute
    # F2 - XF86AudioLowerVolume
    # F3 - XF86AudioRaiseVolume
    # F4 - XF86AudioMicMute
    # F5 - XF86MonBrightnessDown
    # F6 - XF86MonBrightnessUp
    # F7 - XF86Display
    # F8 - XF86WLAN
    # F9 - XF86NotificationCenter
    # F10 - XF86PickupPhone
    # F11 - XF86HangupPhone
    # F12 - XF86Favorites

# =====================================================================
# >> SYSTEM & SESSION CONTROL
# =====================================================================

# =====================================================================
# >> APPLICATION LAUNCHERS
# =====================================================================

# =====================================================================
# >> UTILITY LAUNCHERS
# =====================================================================

# =====================================================================
# >> WINDOW & WORKSPACE MANAGEMENT
# =====================================================================

# =====================================================================
# >> WINDOW & WORKSPACE NAVIGATION
# =====================================================================

# =====================================================================
# >> PYPRLAND
# =====================================================================

# =====================================================================
# >> HARDWARE CONTROLS (Audio, Brightness, etc.)
# =====================================================================
