# =====================================================================
# >> 2nd F-LAYER NAMES & OTHER SPECIAL KEYS
# =====================================================================
    # F1 - XF86HomePage
    # F2 - XF86Explorer
    # F3 - XF86Mail
    # F4 - XF86Tools
    # F5 - XF86AudioPrev
    # F6 - XF86AudioNext
    # F7 - XF86AudioPlay
    # F8 - XF86AudioStop
    # F9 - XF86AudioMute
    # F10 - XF86AudioLowerVolume
    # F11 - XF86AudioRaiseVolume
    # F12 - Notning

# =====================================================================
# >> SYSTEM & SESSION CONTROL
# =====================================================================

# =====================================================================
# >> APPLICATION LAUNCHERS
# =====================================================================

# =====================================================================
# >> UTILITY LAUNCHERS
# =====================================================================

# =====================================================================
# >> WINDOW & WORKSPACE MANAGEMENT
# =====================================================================

# =====================================================================
# >> WINDOW & WORKSPACE NAVIGATION
# =====================================================================

# =====================================================================
# >> PYPRLAND
# =====================================================================

# =====================================================================
# >> HARDWARE CONTROLS (Audio, Brightness, etc.)
# =====================================================================
