source = $HOME/.config/hypr/config/variables/decoration.conf

exec = gsettings set org.gnome.desktop.interface cursor-theme $CURSOR_THEME

exec = gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
exec = gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
exec = gsettings set org.gnome.desktop.interface color-scheme $COLOR_SCHELE

general {
    layout = dwindle
    gaps_in = $WINDOW_MARGIN_IN
    gaps_out = $WINDOW_MARGIN_OUT
    border_size = $BORDER_SIZE
    col.active_border = $ACTIVE_BORDER_COLOR
    col.inactive_border = $INACTIVE_BORDER_COLOR
    resize_on_border = false
    allow_tearing = false
}

animations {
    enabled = 1

    bezier = overshot, 0.13, 0.99, 0.29, 1.15

    # Disable all window and workspace related animations
    animation = windowsIn, 0
    animation = windowsOut, 0
    animation = windowsMove, 0
    animation = border, 0
    animation = fade, 0
    animation = workspaces, 0

    # Keep layers animations for Rofi/notifications/lockscreen
    animation = layersIn, 1, 4, overshot, slide
    animation = layersOut, 1, 4, overshot, slide
}
