input {
    kb_layout = us,no
    kb_variant = altgr-intl,
    kb_model =
    kb_options =
    kb_rules =

    repeat_rate = 50
    repeat_delay = 300

    numlock_by_default = true
    left_handed = false
    follow_mouse = true
    float_switch_override_focus = false

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0 where 0 means no modification.
    accel_profile = flat

    touchpad {
        scroll_factor=0.35
        disable_while_typing=true
        clickfinger_behavior=true # Disables right click in corner
        # middle_button_emulation=true
        tap-to-click=true
        drag_lock=false
    }
}

misc {
    disable_hyprland_logo = true # disables the random Hyprland logo / anime girl background. :(
    disable_splash_rendering = true
    vfr = true
    vrr = 2
    mouse_move_enables_dpms = true
    enable_swallow = true
    swallow_regex = ^(alacritty)$
    focus_on_activate = false
    initial_workspace_tracking = 0
    middle_click_paste = false
    on_focus_under_fullscreen = true
    exit_window_retains_fullscreen = false
}

# # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
# master {
#     new_status = master
# }

binds {
    workspace_back_and_forth = true
    allow_workspace_cycles = true
    pass_mouse_when_bound = false
    movefocus_cycles_fullscreen = true
}

# Helps for scaling and preventing pixelated fonts
xwayland {
    enabled = true
    force_zero_scaling = true
}

# render section for Hyprland >= v0.42.0 # Depricated as of v0.50.0
# render {
#   explicit_sync = 2
#   explicit_sync_kms = 2
#   direct_scanout = 2 #false # Enables direct scanout. Direct scanout attempts to reduce lag when there is only one fullscreen application on a screen (e.g. game). It is also recommended to set this to false if the fullscreen application shows graphical glitches. 0 - off, 1 - on, 2 - auto (on with content type ‘game’)
# }

cursor {
    sync_gsettings_theme = true
    no_hardware_cursors = 2
    enable_hyprcursor = true
    warp_on_change_workspace = false
    no_warps = true
}



debug {
    # Command for viewing last crash/session logs
    # cat $XDG_RUNTIME_DIR/hypr/$(ls -t $XDG_RUNTIME_DIR/hypr | head -n 1)/hyprland.log

    # Command for viewing current session logs
    # cat $XDG_RUNTIME_DIR/hypr/$(ls -t $XDG_RUNTIME_DIR/hypr | head -n 2 | tail -n 1)/hyprland.log
    disable_logs = true

    # hyprctl getoption debug:overlay
    # overlay = true
}