# NOTE: `hypr/config/device.conf` might have exec statements

$SCRIPT_DIR = $HOME/.config/hypr/scripts
$GLOBAL_SCRIPT_DIR = $HOME/.assets/scripts

# Workstation
exec-once = $GLOBAL_SCRIPT_DIR/shell/system/devices/workstation/workstation.sh
#exec = alacritty --hold -e sh $GLOBAL_SCRIPT_DIR/shell/system/devices/workstation/monitor.sh
#exec = $GLOBAL_SCRIPT_DIR/shell/system/devices/workstation/usb.sh

# Event listeners
exec-once = $SCRIPT_DIR/events/system-monitor.sh
exec-once = $GLOBAL_SCRIPT_DIR/shell/system/events/hyprland_socket_listner.sh
exec-once = cargo run --manifest-path $GLOBAL_SCRIPT_DIR/rust/hyprland-event-listener/Cargo.toml

# Startup scripts
exec-once = $GLOBAL_SCRIPT_DIR/shell/system/devices/microphone-validate-state.sh

# Define primary monitor
# TODO: Move this to script that sets current monitors
exec-once = xrandr --output $PRIMARY_MONITOR --primary

# Daemons
exec-once = systemctl --user start hyprpolkitagent

exec = killall dunst; dunst
exec = killall hypridle; hypridle
exec = killall hyprsunset; hyprsunset
exec = killall pypr; pypr

# Background stuff
exec = killall flameshot; flameshot
exec = killall waybar; waybar

# Clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
