$PRIMARY_MONITOR =
$PRIMARY_MONITOR_ASPECT_RATIO =
$SECONDARY_MONITOR =
$SECONDARY_MONITOR_ASPECT_RATIO =

# Needed for Flameshot size calculation
$TOP_LEFT_MONITOR =
$MONITOR_WIDTH_COUNT =
$MONITOR_HEIGHT_COUNT =